### ISSUE TITLE
CUBICSPIRAL Constant IfcAlignmentHorizontalSegmentTypeEnum

### ISSUE THREAD

**Issue by jmirtsch** [bSI-InfraRoom/IFC-Specification#102]
As I understand it, there was a suggestion to remove the CUBICSPIRAL from 
IfcAlignmentHorizontalSegmentTypeEnum, as it's covered by the general CUBIC

This constant is still in the specification at present.  Seeking Clarification.

**Comment by SergejMuhic** [comment]
As I understand it, there was no real CUBICSPIRAL definition coming from the stakeholders. Whenever such a classification was used it turned out to be either the third term of the clothoid Taylor expansion which of course does not represent a spiral but a polynomial.

@apinzenoehler and @czapplitec might have a better insight on rail requirements.

**Comment by apinzenoehler** [comment]
In a informal US paper describing Transition Curve in Road Designs there is indeed a difference between the very badly named "Cubic spirals" and "Cubic Parabola".

the formula for y is in both cases is:

y=l^3 / (6RL)

The difference is in the formula for x:

Cubic spiral: 
x= l * (1 - l^4/(40R^2L^2) + l^8/(3456 R^4 L^4) - ....)

Cubic parabola:
x=l

It is no coincidence that the formula for x in the Cubic spiral seems familiar. It is precisely the formula for x in the Taylor expansion for the clothid. The only difference to the proper clothoid is the shorter formula for y with only the first term. To keep the word "spiral" in the name was a bad decision IMHO. But it seems to be indeed a common name in the US and possibly in the complete Anglo-American world.

Both definitions reflect a "good enough" engineering tradition without need for high precision coordinates. These good enough coordinates will very possibly not conform fully and precisely to the safety related curvature parameters of the segment for kinematic oriented safety checks.

The paper cited at the top contains the following two sentences:

"However, cubic parabolas are more popular due to the fact that they are easy to set out in the field as it is expressed in Cartesian coordinates."

"Despite these are less accurate than cubic spirals, cubic parabolas are preferred by highway and railway engineers, because they are very easy to set."

My takeaway: "Cubic spiral" and "Cubic parabola both are used in road and railway design. The "Cubic spiral" is a simplification of the clothoid, the "Cubic parabola" is used for "drawing based" engineering using Cartesian coordinates.

**Comment by SergejMuhic** [comment]
Thanks for the analysis. Names are quite unfitting though as both seem to be polynomials. Maybe we should have actually just used a polynomial as a type for all these expansion cases?

**Comment by apinzenoehler** [comment]
We received additional feedback from an IFC Rail stakeholder today.

They have a substantial number of Cubics (parabolas) in their network. For **none** of them exists digital (calculated by software) documentation. All of them had been manually calculated and checked for safety regulation conformance a long time ago.

Direct quote from an interview with a domain expert: "If someone asks to represent an existing line it's because there is some renovation work foreseen. We do not draw existing lines for the sake of it. If we renovate/change/modify a line we use clothoids. So, I'd ask the surveyor to use clothoids, and I'll do the same for design of the new alignment."

So from the perspective of the IfcRail stakeholders transition bends in the form of the cubic (parabola or spiral) are not of big importance.

Anyhow, from the perspective of road design, the assessment might be different. Comment from @pjanck , @larswik ?

To be on the safe side I propose to keep both the CUBICPARABOLA and the CUBICSPIRAL in the semantic part. I will provide documentation based on the US paper. The partial templates should also be easy to produce. I suppose that is also true for actual implementation in SW. 

I will include this in the upcoming alignment documentation pull request.

**Comment by larswik** [comment]
Funny enough, there are no mentions of either cubic parabola or cubic spiral in the requirements spec for IFC Road. Neither has it come up at a later stage.

**Comment by pjanck** [comment]
I confirm @larswik : the only transition curves we ever discussed in road design, were clothoids.

**Comment by apinzenoehler** [comment]
@pjanck @larswik Thanks for the input.

I will address participating software vendors and ask for their opinion.

**Comment by jmirtsch** [comment]
The cubic transition is used in Unit Test: Alignment with Cant 7 for the data from RFI /Italferr.
A common ratio could not be identified between segment length and end radius of curvature.
A cubic transition is really for other agencies such as Transport for New South Wales.

**Comment by pjanck** [comment]
I confirm @jmirtsch : there was a requirement from Transport for New South Wales for the cubic transitions, this has been discussed during the DEPL project. How can we address this correctly? I'd at least leave it in the schema and not remove it.

**Comment by jmirtsch** [comment]
CUBICSPIRAL and CUBICPARABOLA seem to be approximations, or have differing definitions in different regions.  x = l as an approximation is not consistent with definitively nominating the shape.  I'd suggest these needs more time and should be removed from the current specification to be refined in future work.

A CUBIC (y = a x^3) is a general mathematical shape, clearly defined.  This was able to represent the RFI sample data in the unit test above.  It's actively used in transitions in parts of Australia and I advocate to include it in this release.

**Comment by SergejMuhic** [comment]
The point of contention is that a cubic is the mathematical term for cubic parabola which is not a term that would define anything. So, cubic parabola = cubic but the term cubic parabola is not correct.
