### ISSUE TITLE
[IFC Tunnel] Updating Voxel grids with higher resolution

### ISSUE THREAD

**Issue by SergejMuhic** [bSI-InfraRoom/IFC-Specification#198]
Voxel grid to reference another grid on a certain position for higher resolution.

[DOCUMENTATION]
[Proposal_GeoSubGroup_2021_06_30_5.pdf](https://github.com/bSI-InfraRoom/IFC-Specification/files/6951387/Proposal_GeoSubGroup_2021_06_30_5.pdf)

**Comment by anborr** [comment]
In the current proposal, the 'IfcVoxelGrid' objects cannot refer to each other in a hierarchical manner, in order to keep the data structure simple. Indeed we propose to use an independent second Grid with finer resolution and place it at the right location. The coarse grid could either have a null datum at this cell or provide an aggregated value.
If however, the feature of references between IfcVoxelGrid is urgently required we have to reconsider or move to future versions of IFC.

**Comment by anborr** [comment]
![grafik](https://user-images.githubusercontent.com/73635642/134466440-5374139a-0fb3-470f-8e14-a9e85ef27a80.png)
