### ISSUE TITLE
Property sets are missing from documentation

### ISSUE THREAD

**Issue by RickBrice** [bSI-InfraRoom/IFC-Specification#258]
The latest (unofficial) documentation at http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/ does not contain property sets. In the old format Property Sets were in B.1.7.

Using the search feature for Pset_PrecastConcreteElementGeneral gives the following link but leads to a "URL not found" error.

http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/Pset_PrecastConcreteElementGeneral.htm

**Comment by pjanck** [comment]
Hi @RickBrice 

this issue is better suited to be posted with the source repository for that documentation: https://github.com/buildingSMART/IFC4.3.x-development

A word of caution: as far as I know, it is a work in progress and not to be considered "final" until ISO approval. Why is it linked on the official list of IFC documentations, or in "release" folder, is beyond my comprehension.

**Comment by RickBrice** [comment]
@pjanck - Thanks - Just trying to be helpful. The IFC documentation is quite massive so I'm sure it is easy to miss infrequently checked details.
