### ISSUE TITLE
IfcSurfaceFeature needs a new rel?

### ISSUE THREAD

**Issue by pjanck** [bSI-InfraRoom/IFC-Specification#28]
Looking at `IfcFeatureElement` and its subtypes:

- `IfcFeatureElementSubtraction` has its own specialized `IfcRelVoidsElements` relationship
- `IfcFeatureElementAddition` has its own `IfcRelProjectsElement` relationship
- `IfcSurfaceFeature`  has none.

1. Perhaps a specialized relationship inheriting from `IfcRelDecomposes` would be in place?
2. Perhaps changing the supertype to `IfcFeatureElementAddition`?

Context: https://github.com/bSI-InfraRoom/IFC-infra-unit-test/pull/88

**Comment by SergejMuhic** [comment]
There is a third option. Adding an inverse to IfcRelDecomposes and a WR that restricts it to IfcRelVoidsElements and IfcRelProjectsElements.

**Comment by SergejMuhic** [comment]
Resolution: add IfcRelAdheres relationship.

**Comment by AlexBrad1eyCT** [comment]
I like that, so much more technical than "IfcRelSticksTo" ! :P

**Comment by larswik** [comment]
Something like this?
- Add **IfcRelAdheresElement** ENTITY
  - Parallel to IfcRelVoidsElement (SUBTYPE OF IfcRelDecomposes)
  - **RelatingElement : IfcElement**
  - **RelatedAdheringElement : IfcSurfaceFeature**

Definition: 
IfcRelAdheresElement is an objectified relationship between an element and one surface feature element that adheres to the surface on the element. It is a one-to-one relationship. 

There is a pull request https://github.com/bSI-InfraRoom/IFC-infra-unit-test/pull/88 for a unit test. 
Two alternatives:
1. Complete this task (above) and modify unit test accordingly (change relationship type)
2. Keep schema as is and modify unit test so that each IfcCourse entity aggregates an IfcCourse + the IfcSurfaceFeature to keep geometry at the lowest level.

**Comment by AlexBrad1eyCT** [comment]
I have authored a first draft in #64
