### ISSUE TITLE
Add Pset_Stationing.Increasing : IfcBoolean

### ISSUE THREAD

**Issue by SergejMuhic** [bSI-InfraRoom/IFC-Specification#348]
We have a requirement to add this property. I would ask @clfey to add the description for it. We can submit it in the PR.

https://github.com/buildingSMART/IFC4.3.x-development/issues/169

**Comment by clfey** [comment]
### Text proposal for `Increasing`
The `Increasing` attribute is an optional attribute of the `Pset_Stationing` property set. It is meant for use in referents of predefined type REFERENCEMARKER being nested to a given alignment.

If present and `true`, or if not present, then the relevant subsequently nested STATION referents are generally expected to have `Pset_Stationing.Station` values being larger than the REFERENCEMARKER's `Pset_Stationing.Station` value.

If present and `false`, then the relevant subsequently nested STATION referents are expected to have `Pset_Stationing.Station` values being lower than the REFERENCEMARKER's `Pset_Stationing.Station` value.

See also the tutorial text on LRM concepts (link:#0000).

**Comment by clfey** [comment]
I added the word "generally" to paragraph 2 above. This leaves an opening for an interpretation where Increasing/Decreasing is rather deduced from two subsequent reference markers. In this use case, the Increasing attribute shall not be used since it is redundant and since its value could be contradictory to the increasing / decreasing direction as deduced from a Station followed by an  lower / higher IncomingStation.

See details in issue #350.
