### ISSUE TITLE
IfcDocLite

### ISSUE THREAD

**Issue by aothms** [bSI-InfraRoom/IFC-Specification#382]
Two questions:

Is the source code of IfcDocLite available?

It doesn't seem the XSD export is implemented? I only see -FE (express) -FP (props) -FS (folder structure) and -D (docs)

**Comment by SergejMuhic** [comment]
> Is the source code of IfcDocLite available?

I could make it available. I haven't yet because it is poorly documented and I would have to put some license/copyright on it I guess.

> It doesn't seem the XSD export is implemented? I only see -FE (express) -FP (props) -FS (folder structure) and -D (docs)

True. Docs kind of generated everything anyway, so there was no special requirement for this part. Since I kind of just add stuff based on when any needs arise 😄 , I could add that also.

This app is not my priority though, so I have a long turnaround time.

Let me know if anything is of interest.

**Comment by aothms** [comment]
Ok, I didn't realize that -D did everything, I should have checked. Then for me it's also not a high priority thing. I'll just close this then. Thanks for the reply.
