### ISSUE TITLE
Unused IfcBearingTypeDisplacementEnum

### ISSUE THREAD

**Issue by aothms** [bSI-InfraRoom/IFC-Specification#462]
What's the purpose of IfcBearingTypeDisplacementEnum, introduced in 4x2 but never referenced? Is it obsolete, should it have been a PEnum? Anybody any ideas?

https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC4-voting/HTML/link/ifcbearingtypedisplacementenum.htm

**Comment by SergejMuhic** [comment]
Hm, I cannot remember this. It seems superfluous. It also does not seem to be finished since it does not features `USERDEFINED`. @anborr do you remember what the rationale behind this enum was?

Since you say that it is never referenced, I would assume it has no purpose anymore. Might just be a ghost leftover.

**Comment by pjanck** [comment]
Seems fixed by #477
