### ISSUE TITLE
Shouldn't be IfcAxis2PlacementLinear.Axis taken from the curve tangent instead of IfcAxis2PlacementLinear.RefDirection?

### ISSUE THREAD

**Issue by Nadia-Sugar** [bSI-InfraRoom/IFC-Specification#49]
I would expect IfcAxis2PlacementLinear.Axis to be taken from the curve tangent instead of IfcAxis2PlacementLinear.RefDirection, because IfcProfileDef-s are usually placed within the XY plane of the 3D position coordinate system of the geometrical entity and the profile normal IfcAxis2PlacementLinear.Axis should then agree with the tangent of the directrix. Even the IfcSectionedSolidHorizontal documentation suggests that:

"The solid is generated by sweeping the CrossSections between CrossSectionPositions with linear interpolation of profile points, where **the profile normal agrees with the tangent of the Directrix, the profile X axis is oriented perpendicularly to the left of the Directrix** (same direction as LateralOffset at IfcPointByDistanceExpression) as facing forward along the directrix, and **the profile Y axis is oriented upwards** according to FixedAxisVertical."

Thanks a lot
Nadia

**Comment by pjanck** [comment]
My interpretation of the concepts:

1. `IfcAxis2PlacementLinear`
   - interpretation happens independent of the `IfcSectionedSolidHorizontal` (as it is used elsewhere as well)
   - its `RefDirection` (should it not be provided) defaults to the tangent of the curve
   - the `Axis` is given - defines z
   - one can calculate x,y,z from these data
2. `IfcSectionedSolidHorizontal`
   - profiles are defined in their own x,y,z - let's call that system u,v,w for clarity
   - one sets w -> x, then u -> y and v -> x
   - voila

I think that a change in the documentation for `IfcSectionedSoldHorizontal` is necessary here in order to reflect this.

**Comment by SergejMuhic** [comment]
Addressed in a test. 6acec7aa4f52394c75d14dc10405d990dc47b23e
