### ISSUE TITLE
PredefinedType of IfcBoreHole

### ISSUE THREAD

**Issue by jmirtsch** [bSI-InfraRoom/IFC-Specification#503]
Classes representing instances with an attribute PredefinedType are typically optional.
Most instances have a relating type, but boreholes don't.  I'd suggest the attribute should be optional, but perhaps I'm not aware of a strategy to make them mandatory if there is no explicit relating type.

**Comment by SergejMuhic** [comment]
With no `IfcTypeObject` `PredefinedType` should be mandatory since it has to be set. In the case of an appropriate `IfcTypeObject` being present in the schema, the `PredefinedType` on `IfcElementType` is mandatory. The where rules consequently have to be applied appropriately.

I would expand this question to why are there no related `IfcTypeObject` entities for `IfcBorehole` and `IfcGroundReinforcementElement`?

For all the infra added elements, we eventually added the IfcElementType entities.

**Comment by larswik** [comment]
IfcBorehole didn't have an IfcBoreholeType in IFC 4.3 but in my opinion, it could make sense to add it. Maybe need to ask the geotech domain group first? For IfcGroundReinforcementElement I think that it is only en oversight which I will fix without asking.

**Comment by jmirtsch** [comment]
IfcGeomodel and IfcGeoslice seem to be two classes that are a sub type of IfcElement that also don't have a predefined type attribute.

**Comment by larswik** [comment]
> IfcGeomodel and IfcGeoslice seem to be two classes that are a sub type of IfcElement that also don't have a predefined type attribute.

This is correct. Also IFC 4.3. These entities were considered not useful by the IFC Tunnel geoscience domain team and should maybe even be deprecated? We didn't touch these so far.

Regarding IfcBorehole, I sent a question to our geoscience team whether they see a need for an IfcBoreholeType entity.

**Comment by larswik** [comment]
There is a decision in the email dated 2023-07-13 20:59 from @Michel-Rives:
07-13>> had an exchange with the Domain team and confirmed: please have /IfcBoreholeType.
Was this done? I can't find a corresponding PR. Ping @SergejMuhic
