### ISSUE TITLE
Pset for linearly referenced positioning on semantic level

### ISSUE THREAD

**Issue by larswik** [bSI-InfraRoom/IFC-Specification#52]
Similarly to the structure for alignments, there are requirements to enable linear referencing also when geometry does not exist in a file. Proposal:
- There is already a **PredefinedType=POSITION** for **IfcReferent**
- Define a **Pset_DistanceExpression** applicable to the above (according to ISO 19148, DistanceExpression)
- Pset properties:
  - **Station : IfcLengthMeasure** (used in the same way as in Pset_Stationing)
  - **OffsetLateralDistance : IfcLengthMeasure**
  - **OffsetVerticalDistance : IfcLengthMeasure**
- Positive directions (and units if other than project length units) are defined by another new **Pset_LRMWithOffset** with properties (according to ISO 19148 - LRMWithOffset)
    - **OffsetUnit : IfcLabel**
    - **PositiveLateralOffsetDirection : PEnum_LateralOffsetDirection** {"LEFT","RIGHT"}
    - **PositiveVerticalOffsetDirection : PEnum_VerticalOffsetDirection** {"UP","DOWN"}
Left, right, up and down relates to the direction defined by the ordering of nested IfcReferent/REFERENCEMARKER

**Comment by larswik** [comment]
After discussions with Chi, maybe Pset_LinearPositionExpression (and still reference ISO 19148) would be a better name than Pset_DistanceExpression. Everything else same.

**Comment by SergejMuhic** [comment]
I do not understand the positive direction relying on IfcReferent/REFERENCEMARKER. Relying on its Placement? Just an order does not yet uniquely define the directions.

**Comment by larswik** [comment]
Moving from one referent towards another defines a direction doesn't it?

**Comment by czapplitec** [comment]
I looked into the ISO 19148. Compared with Pset_LinearReferencingMethod, the LinearReferencingMethod in ISO19148 has one more property positiveDistanceAlongDirection, which as you said, can be replaced by the ordering of nested IfcReferent/ReferenceMarker placed along the alignment. This implies that in order to let “LEFT/RIGHT” make sense for "position", the IFC file has to have geometry.

Considering we may exchange information without geometry in some scenarios, I think in Pset_LinearReferencingMethod, still add the property PositiveDistanceAlongDirection, True means the direction follows the ordering of IfcAlignmentSegment in IfcAlignmentHorizontal, False means reverse the direction. This also means if it is false, then the list of IfcReferent/REFERENCEMARKER is in the scenario of inverse stationing.

**Comment by SergejMuhic** [comment]
Resolved in #16
