### ISSUE TITLE
Ifc???OrderPolynomialSpiral => new entity with not Second, Third but at least 7th order polynomial spiral

### ISSUE THREAD

**Issue by peterrdf** [bSI-InfraRoom/IFC-Specification#55]
To be able to support Vienesse Bend transition curves we need a new sub entity of Spiral with at least a 7th order polynomial spiral (in line with IfcSecondOrderPolynomialSpiral and IfcThirdOrderPolynomialSpiral). There are two proposals:

ENTITY IfcTenthOrderPolynomialSpiral / IfcHigherOrderPolynomialSpiral
 SUBTYPE OF (IfcSpiral);
    DecicTerm : OPTIONAL IfcLengthMeasure;
    NonicTerm : OPTIONAL IfcLengthMeasure;
    OcticTerm : OPTIONAL IfcLengthMeasure;
    SepticTerm : OPTIONAL IfcLengthMeasure;
	SexticTerm : OPTIONAL IfcLengthMeasure;
    QuinticTerm : OPTIONAL IfcLengthMeasure;
	QuarticTerm : OPTIONAL IfcLengthMeasure;
	QubicTerm : OPTIONAL IfcLengthMeasure;
	QuadraticTerm : OPTIONAL IfcLengthMeasure;
	LinearTerm : OPTIONAL IfcLengthMeasure;
	ConstantTerm : OPTIONAL IfcReal;
 WHERE 
    HasTerms : EXISTS (DecicTerm) OR EXISTS (NonicTerm) OR EXISTS (OcticTerm) OR 
 EXISTS (SepticTerm) OR EXISTS (SexticTerm) OR EXISTS (QuinticTerm) OR 
 EXISTS (QuarticTerm) OR EXISTS (QubicTerm) OR EXISTS (QuadraticTerm) OR EXISTS (LinearTerm);
END_ENTITY;

or alternatively

ENTITY IfcPolynomialSpiral
 SUBTYPE OF (IfcSpiral);
    Degrees : LIST [1:?] OF IfcInteger;
    Terms : LIST [1:?] OF IfcLengthMeasure;
	ConstantTerm : OPTIONAL IfcReal;
 WHERE
   CorrespondingDegreeTerms : SIZEOF(Degrees)=SIZEOF(Terms);
END_ENTITY;

**Comment by SergejMuhic** [comment]
Could we get a Viennese bend specification?

**Comment by AlexBrad1eyCT** [comment]
From a purely efficient modelling perspective and simplification of implementation by vendors, @peterrdf second proposal:

> ENTITY IfcPolynomialSpiral
> SUBTYPE OF (IfcSpiral);
>    Degrees : LIST [1:?] OF IfcInteger;
>    Terms : LIST [1:?] OF IfcLengthMeasure;
>    ConstantTerm : OPTIONAL IfcReal;
> WHERE
>    CorrespondingDegreeTerms : SIZEOF(Degrees)=SIZEOF(Terms);
> END_ENTITY

is far more elegant and manageable from a software perspective than the current proposed solution of the multiple entities... IfcSecondOrderPolymonialSpiral, IfcThirdOrderPolymonialSpiral, Ifc???OrderPolymonialSpiral.

**Comment by TLiebich** [comment]
I have to admit that I am lost after the third or forth order ;-)

but what I understand of the original proposal is, that there are length measures of a particular order (and labelled as such), that may exists independently of each other. An alternative modeling solution could be to use a sparse array, i.e. an array, where, at a particular position of the array, values could be nil.

ENTITY IfcPolynomialSpiral
  SUBTYPE OF (IfcSpiral);
    OrderOfSpiral : IfcPositiveInteger;
    Terms : ARRAY [1:OrderOfSpiral] OF OPTIONAL IfcLengthMeasure;
    ConstantTerm : OPTIONAL IfcReal;
  WHERE
    MaximalOrder : OrderOfSpiral <= 10;
END_ENTITY

the position of the length measure within the array determines its order. Since the array allows for NIL values, not all orders have to be presented by values (if this is desired). An ARRAY in EXPRESS cannot the unbounded, but it is allowed to be a numeric expression. I took the highest order from Peters original proposal as being 10. 

in an exchange, if would be

001 = IFCPOLYNOMINALSPIRAL ("...attributes.of.spiral...", 4, [1.0, $, 1.0, $], $)

this is elegant in EXPRESS, not sure how well it maps to UML and similar.

**Comment by SergejMuhic** [comment]
Resolved in #61
