### ISSUE TITLE
Documentation for IfcSectionedSolid may be incorrect.

### ISSUE THREAD

**Issue by RickBrice** [bSI-InfraRoom/IFC-Specification#82]
IfcSectionedSolid.Directrix attribute is of type IfcCurve. The DirectrixIs3D rule states that the curve entity underlying directrix shall have a dimensionality of 3.

The attached models have IfcSectionedSolidHorizontal entities where the Directrix is an IfcPolyline in one case and an IfcAlignmentCurve in the other. The IfcPolyline is constructed from IfcCartesianPoint with 3 dimensions (X,Y,Z) thus satisfying the dimensionality of 3 rule.

When viewed in ODA's Open IFC Viewer 22.5, the entities using an IfcPolyline are not created but are created for the IfcAlignmentCurve. Other IfcCurve derived objects where used as the Directrix as well. The only one that would produce a shape in ODA's view is IfcAlignmentCurve.

Not sure if this is an implementation problem or the documentation needs to be updated by being more specific about which IfcCurve subtypes are appropriate for use with IfcSectionedSolidHorizontal.

[SectionedSolidHorizontalExamples.zip](https://github.com/bSI-InfraRoom/IFC-Specification/files/6678716/SectionedSolidHorizontalExamples.zip)

**Comment by SergejMuhic** [comment]
I would think that the ODA toolkit requires an update then. I will try this dataset with the IfcKit toolkit and can also distribute to other participating partners. Will get back to you.

**Comment by SergejMuhic** [comment]
Forgot I also have RDF available. The outcome:
1. Had no problems with IfcKit nor my toolkit, files looked quite alright (only tree view no visualization)
2. Tried it with the RDF viewer, also looks okay (just not sure if it got everything, could be that IfcSectione):
![image](https://user-images.githubusercontent.com/16683597/122819732-1cee9280-d2db-11eb-8cf8-384f0d293467.png)

The deck is obviously problematic as IfcAlignmentCurve was deprecated almost one year ago.

Can also ask @jmirtsch to have a look but I think we are on a good track here.

**Comment by RickBrice** [comment]
Thanks for the feedback. I'm trying to learn IFC using IfcOpenShell as a parser engine and model builder. Seems that I get different results for every viewer I try so I have not idea if I'm building models correctly - frustrating.

The 4x3 specification still has refences to IfcAlignmentCurve ( #51).  I'm using the 4x1 specification which has IfcAlignmentCurve, though this spec is listed as Withdrawn.

**Comment by SergejMuhic** [comment]
The exp file you linked there does not feature an IfcAlignmentCurve anymore. Otherwise, for the latest schema just go to Actions and select the schema-generation workflow and download artifacts:
https://github.com/bSI-InfraRoom/IFC-Specification/actions/workflows/schema-generation.yml

**Comment by jmirtsch** [comment]
Hi Rick, 
I'd also suggest that you are experiencing implementation issues.  I tried importing both your files with expected results in the Geometry Gym plugin for Rhino3d.  Certainly it would make it easier for new implementations if viewers etc could produce verbose logs if they encounter errors or have not supported a feature.  It's common for errors to be swallowed and objects not rendered.

![210622 rhino sectioned solid](https://user-images.githubusercontent.com/791757/122882609-b7a0ad00-d37f-11eb-8814-f3e4a27d23df.png)

I have one comment to improve your file (other than looking at the IFC4.3 improvements rather than IFC4.1)  The polylines defining profile for deck and railing seems to be open, ie the last point is not the same (or coincident) with the start point.   

Cheers,

Jon

**Comment by larswik** [comment]
I tried the Acca viewer. Didn't render the deck and railings, probably due to the issues with the profiles. However, the girders renders fine regardless of the type of directrix. I also tried BIMVision which obviously doesn't support IfcSectionedSolidHorizontal  at all at this point.
![image](https://user-images.githubusercontent.com/25506404/122894863-df741e80-d347-11eb-81d0-4d283807b01d.png)
![image](https://user-images.githubusercontent.com/25506404/122895105-15b19e00-d348-11eb-9b06-d2677f15cae8.png)

**Comment by RickBrice** [comment]
Thank you all for the feedback. I'll check out some of the viewers you have mentioned. The issues seem to be two-fold; not all viewers work correctly and the IFC-SPF code I've generated could use some improvements - I guess stepping up to the 4x3 spec would be a good idea as well.
