### ISSUE TITLE
[IFC-Tunnel] Documentation for Scale in IfcMapConversion

### ISSUE THREAD

**Issue by SergejMuhic** [bSI-InfraRoom/IFC-Specification#87]
Update the documentation of the Scale attributes according to proposal of @Moult:

https://github.com/buildingSMART/IFC4.3.x-development/issues/43#issuecomment-864654176

**Comment by Moult** [comment]
Just a note that I am not qualified to guarantee the correctness of these proposals, so you should wait for @LeeGregory12d to confirm.

**Comment by SergejMuhic** [comment]
> 
> 
> Just a note that I am not qualified to guarantee the correctness of these proposals, so you should wait for @LeeGregory12d to confirm.

Definitely. It is also just a proposal that will be run through an IFC Tunnel Expert panel July 5th. Welcome to join!

**Comment by pjanck** [comment]
Proposal for the documentation:

> Scale by which the length measures of the geometric content have to be multiplied to get correct map length measures. This happens when the length units of the `TargetCRS` and `SourceCRS` are different (e.g. IFC content is in feet, while the IfcProjectedCRS defines meters). If omitted, the value of 1.0 is assumed.

I'm not quite happy with the wording, so improvement is very welcome!

I'd remove the different scales for X, Y and Z and have one scale factor, since neither `IfcContext` nor `IfcCoordinateReferenceSystem` are capable of defining different length measures for individual coordinate axes; at least not that I'm aware of.

**Comment by LeeGregory12d** [comment]
Stefan,

Where did that definition come from?
The definition is totally wrong.

As far as I know it has nothing to do with conversion between feet and metres.
And if it has then everything we did in IFC Model Setup IDM since 2016.

As far as I’m concerned, allowing for an Sx and a Sy is one of the most important addition to IFC 4x3 for Civil Infrastructure  since Alignments and Tins IFC 4x1.

Regards
Lee

Dr Lee Gregory
Managing Director
12D Solutions Pty Ltd

Creators of the 12d Model Civil and Surveying Software
and 12d Synergy for Data Management and Project Collaboration.
Ph: +61 (0)2 9970 7117
Email: ***@***.******@***.***>
Web: www.12d.com<http://www.12d.com/aus/?utm_source=emailsig&utm_medium=email&utm_campaign=emaillink>

**Comment by TLiebich** [comment]
agree with @LeeGregory12d - looks that the old (and wrong) definition still persists. Scale shall not deal with the unit conversion between the unit used in the map according to the ESPG code and the agreed usage of the _Unit_ attribute.

My understanding is, that it handles the value of distortion (? unsure about the terminology here) or the fact, that a map length is not the same as the field length. My understanding from earlier discussion is also, that the value differs between easting, northing and height.

best to find a better name for the attribute instead of _Scale_

**Comment by Moult** [comment]
I'm not sure why the discussion is happening here - there has already been a proposed definition here: https://github.com/buildingSMART/IFC4.3.x-development/issues/43

**Comment by SergejMuhic** [comment]
> 
> 
> agree with @LeeGregory12d - looks that the old (and wrong) definition still persists. Scale shall not deal with the unit conversion between the unit used in the map according to the ESPG code and the agreed usage of the _Unit_ attribute.
> 
> My understanding is, that it handles the value of distortion (? unsure about the terminology here) or the fact, that a map length is not the same as the field length. My understanding from earlier discussion is also, that the value differs between easting, northing and height.
> 
> best to find a better name for the attribute instead of _Scale_

The problem with such a definition is that this factor is not constant. It is also not needed as the identifier from EPSG (or any other classification systems) is enough and with the WKT behind these classification supplies all the information needed for a conversion.

If this is the purpose of scale, I would just remove it as it only introduces confusion.

**Comment by Moult** [comment]
I was under the impression that the scale factor is constant given a small site, where a small site is defined as less than 1km square.

**Comment by SergejMuhic** [comment]
It is never constant. If a constant value is given, it is an approximation.

From my knowledge, the code is just pointing to a WKT that provides all the information for conversion, so, if scale is supposed to be used for that purpose, it is redundant and misleading since it is an approximation. We are also looking at big datasets in infra and this single scale value would definitely not be sufficient.

Each code has a WKT and GML specification which give the actual conversion data (marked yellow):
![image](https://user-images.githubusercontent.com/16683597/126624291-d2d37509-c74f-4c99-91c3-4ae70ef7283b.png)

This is how other "classification systems" for coordinate system conversion also do it.

**Comment by LeeGregory12d** [comment]
Sorry to be a party pooper but:

The "scale " being discussed is not the "projection scale factor" referred to in WKT and GML specification. 
It is the "combined scale factor" or "ground to grid factor" or "grid factor".

And yes this value is not constant and varies with (X,Y) position AND height.

BUT if you stick to a small enough region, without too much difference in height, then the combined scale factor can be taken as a constant in that restricted area. 
What size and shape that area actually is depends on the map projection, height differences and what accuracy you want when converting map distance to ground distances and vice-versa.

On most Infrastructure projects this is not  an issue because the data is usually recorded in map coordinates and geoid heights.

The only time problems occur is when someone uses a "local engineering system" on some part of the project.
Then of course that data needs to be converted to map coordinates to fit in with all the other project data and so a combined scale factor is needed for the conversion from the "local engineering coordinates" to "map coordinates (projection) coordinates".

And the word "local" is in there for a reason - the part of a project has to be kept to a small area so that the combined scale factor can be taken to be a constant.

This has been discussed in more detail in the "Model setup IDM". 

**Note:**
"Scale" could be dropped if all the data in the IFC file was in map coordinates which is what I think the IFC Tunnel project has proposed.
But in that case, anyone working in a local engineering coordinates would need to do the conversion themselves before writing out the IFC file.
One consequence of this is that the original  "local engineering coordinates" are then lost and if an error was made in any of the conversion, there is no way of backtracking.

The value of using IfcMapConversion and providing the combined scale factors in there means that the rest of the data in the file can be in the original local engineering coordinates and you know from the parameters in IfcMapConversion EXACTLY what the 3D translation, rotation in the (X,Y) plane and scale factors that are to be used to go from the local engineering coordinates for that small area to the map coordinates for the infrastructure project.
So if someone screwed up calculating the parameters, you still have the original local engineering data in the IFC file and only have to correct the IfcMapConversion parameters.
